# Generated by Django 5.2.1 on 2025-10-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatchstats',
            name='bowling_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='overs_bowled',
            field=models.FloatField(default=0.0),
        ),
    ]
